# Generated by Django 2.0.2 on 2018-02-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='type',
        ),
    ]
