# Generated by Django 2.0.2 on 2018-02-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_remove_menuitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
