# Generated by Django 2.0.2 on 2018-02-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_menuitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, choices=[('appertizer', 'appertizer'), ('sashimi', 'sashimi'), ('nigiri', 'nigiri'), ('sushi rolls', 'sushi rolls'), ('beverage', 'beverage')], max_length=200, null=True),
        ),
    ]
