# Generated by Django 2.0.2 on 2018-02-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_auto_20180225_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='number',
        ),
    ]
